### ISSUE TITLE
Dynamic instructions and code sample

### ISSUE THREAD

**Issue by DawoodLaiq** [SanjinDedic/agent_games#44]
Need an endpoint where I send in the league name and game name. In response I need the json for the starter game instructions and the code sample in json.

Here is an example for the code sample

'from games.greedy_pig.player import Player\n\nclass CustomPlayer(Player):\n\tdef make_decision(self, game_state):\n\t\tif game_state["unbanked_money"][self.name] > 5:\n\t\t\treturn 'bank'\n\t\treturn 'continue'\n'

First four lines are always not editable by default on the front end.

For instructions. Right now I have this
<div className="instructions-container">
                  <h1>Competition Instructions</h1>
                  <ol>
                      <li>
                          <strong>Login Process</strong>
                          <p>Click on the <b>Game Submission</b> option in the navbar to log in.</p>
                      </li>
                      <li>
                      </ol>
                      </div>
                      
Need an identifier for listed items, headings and bold texts.

**Comment by SanjinDedic** [comment]
You need to clarify the issue. 

I am assuming that this is what you want:

endpoint
```python3 
@app.get("/", response_model=ResponseModel)
def get_published_results_for_all_leagues(session: Session = Depends(get_db), game_type='greedy_pig'):
```

Return value:
```json
{
  "starter_code": "from games.greedy_pig.player import Player\n\nclass CustomPlayer(Player):\n\tdef make_decision(self, game_state):\n\t\tif game_state['unbanked_money'][self.name] > 5:\n\t\t\treturn 'bank'\n\t\treturn 'continue'\n' ", 
  "game_instructions": "These are the instructions"
}
```



If so can you update the description and provide formatted strings for both starter code and the instructions so that they will display correctly on the website

**Comment by SanjinDedic** [comment]
Please test out the new branch and review the pull request. Comment below with the updated strings if appropriate

**Comment by DawoodLaiq** [comment]
Tested the branch and It was successful. Will explain the issues clearly and easily in the future.
