### ISSUE TITLE
Troubleshoot invalid token breaking pages

### ISSUE THREAD

**Issue by SanjinDedic** [SanjinDedic/agent_games#64]
This is what needs fixing:

when the token is invalid (from a different session or expired) 

The login page and the submission no longer works.

So try validating the token fist and if invalid clearing local storage.

**Comment by DawoodLaiq** [comment]
Session storage is added instead of local storage so when a user is active the redux state is active only that time.

For expiry of auth tokens. The expiry date and time created from the backend is not fixed so we need to assign it to only one specific time zone.
